// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: proto/error_growth_center.proto

package xerr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	_ "test/errors"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrowthCenterErrorState int32

const (
	// biz error
	// 系统:growth_center 13
	// 模块:通用 00
	GrowthCenterErrorState_GROWTH_CENTER_GET_USERINFO_FAILED GrowthCenterErrorState = 0
)

// Enum value maps for GrowthCenterErrorState.
var (
	GrowthCenterErrorState_name = map[int32]string{
		0: "GROWTH_CENTER_GET_USERINFO_FAILED",
	}
	GrowthCenterErrorState_value = map[string]int32{
		"GROWTH_CENTER_GET_USERINFO_FAILED": 0,
	}
)

func (x GrowthCenterErrorState) Enum() *GrowthCenterErrorState {
	p := new(GrowthCenterErrorState)
	*p = x
	return p
}

func (x GrowthCenterErrorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrowthCenterErrorState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_error_growth_center_proto_enumTypes[0].Descriptor()
}

func (GrowthCenterErrorState) Type() protoreflect.EnumType {
	return &file_proto_error_growth_center_proto_enumTypes[0]
}

func (x GrowthCenterErrorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrowthCenterErrorState.Descriptor instead.
func (GrowthCenterErrorState) EnumDescriptor() ([]byte, []int) {
	return file_proto_error_growth_center_proto_rawDescGZIP(), []int{0}
}

var File_proto_error_growth_center_proto protoreflect.FileDescriptor

var file_proto_error_growth_center_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x67, 0x72,
	0x6f, 0x77, 0x74, 0x68, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x78, 0x65, 0x72, 0x72, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x76, 0x0a, 0x16,
	0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4a, 0x0a, 0x21, 0x47, 0x52, 0x4f, 0x57, 0x54, 0x48,
	0x5f, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x1a, 0x23, 0xb8,
	0x45, 0x00, 0xc0, 0x45, 0xa0, 0xac, 0x4f, 0xca, 0x45, 0x18, 0xe8, 0x8e, 0xb7, 0xe5, 0x8f, 0x96,
	0xe7, 0x94, 0xa8, 0xe6, 0x88, 0xb7, 0xe4, 0xbf, 0xa1, 0xe6, 0x81, 0xaf, 0xe5, 0xa4, 0xb1, 0xe8,
	0xb4, 0xa5, 0x1a, 0x10, 0xa0, 0x45, 0x00, 0xa8, 0x45, 0x01, 0xb2, 0x45, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x42, 0x0f, 0x5a, 0x0d, 0x69, 0x64, 0x6c, 0x2f, 0x78, 0x65, 0x72, 0x72,
	0x3b, 0x78, 0x65, 0x72, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_error_growth_center_proto_rawDescOnce sync.Once
	file_proto_error_growth_center_proto_rawDescData = file_proto_error_growth_center_proto_rawDesc
)

func file_proto_error_growth_center_proto_rawDescGZIP() []byte {
	file_proto_error_growth_center_proto_rawDescOnce.Do(func() {
		file_proto_error_growth_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_error_growth_center_proto_rawDescData)
	})
	return file_proto_error_growth_center_proto_rawDescData
}

var file_proto_error_growth_center_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_error_growth_center_proto_goTypes = []interface{}{
	(GrowthCenterErrorState)(0), // 0: xerr.GrowthCenterErrorState
}
var file_proto_error_growth_center_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_error_growth_center_proto_init() }
func file_proto_error_growth_center_proto_init() {
	if File_proto_error_growth_center_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_error_growth_center_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_error_growth_center_proto_goTypes,
		DependencyIndexes: file_proto_error_growth_center_proto_depIdxs,
		EnumInfos:         file_proto_error_growth_center_proto_enumTypes,
	}.Build()
	File_proto_error_growth_center_proto = out.File
	file_proto_error_growth_center_proto_rawDesc = nil
	file_proto_error_growth_center_proto_goTypes = nil
	file_proto_error_growth_center_proto_depIdxs = nil
}
