// Code generated by gen-go-errors. DO NOT EDIT.

package xerr

import (
	fmt "fmt"
	errors "test/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// biz error
// 系统:growth_center 13
// 模块:通用 00
func IsGrowthCenterGetUserinfoFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 1300000
}

// biz error
// 系统:growth_center 13
// 模块:通用 00
func ErrorGrowthCenterGetUserinfoFailed(format string, args ...interface{}) *errors.Error {
	if format == "" {
		return errors.New(errors.Stat_FAILED, 1300000, "获取用户信息失败")
	}
	return errors.New(errors.Stat_FAILED, 1300000, fmt.Sprintf(format, args...))
}
