// Code generated by gen-go-errors. DO NOT EDIT.

package xerr

import (
	fmt "fmt"
	errors "test/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// biz error
// 系统:sequel 11
// 模块:通用 00
func IsSequelGetUserinfoFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 1100000
}

// biz error
// 系统:sequel 11
// 模块:通用 00
func ErrorSequelGetUserinfoFailed(format string, args ...interface{}) *errors.Error {
	if format == "" {
		return errors.New(errors.Stat_FAILED, 1100000, "获取用户信息失败")
	}
	return errors.New(errors.Stat_FAILED, 1100000, fmt.Sprintf(format, args...))
}

func IsSequelGetPayUrlFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 1100001
}

func ErrorSequelGetPayUrlFailed(format string, args ...interface{}) *errors.Error {
	if format == "" {
		return errors.New(errors.Stat_FAILED, 1100001, "报名失败")
	}
	return errors.New(errors.Stat_FAILED, 1100001, fmt.Sprintf(format, args...))
}
